### ISSUE TITLE
饼呢？

### ISSUE THREAD

**Issue by nvkou** [MaaAssistantArknights/MaaCopilotServer#1]
- [ ] 用例？
- [ ] 选型？
- [ ] roadmap？

**Comment by Shawnsdaddy** [comment]
在写了（新建文件夹）

**Comment by MistEO** [comment]
你写了就有了.jpg

**Comment by Shawnsdaddy** [comment]
基本框架已经答完，本地已经实现。

TODO: 
1. 编写GET API 逻辑 
2.增加Logmiddleware
3. 增加点赞表（需要讨论）
