### ISSUE TITLE
[Refactor] 重构 Server

### ISSUE THREAD

**Issue by LYZhelloworld** [MaaAssistantArknights/MaaCopilotServer#14]
Server 中的一些组件可能需要进一步的重构以便于将来的开发和测试。

目前各个项目的用途分别为（@LiamSho）：
- `Api`：接收HTTP请求
- `Application`：具体的业务逻辑、DTO
- `Domain`：各种实体
- `Infrastructure`：一些通用服务和数据库对接

## 重构任务（按优先级从高到低）
- [x] #15
- [x] #17 @LiamSho
- [x] #22
- [x] #24
- [x] #25
- [x] #32

## 已取消
- ~~将 DTO 类跟数据库实体存放到一个项目中。~~
- ~~#18~~

**Comment by LYZhelloworld** [comment]
> > 将 DTO 类跟数据库实体存放到一个项目中。
> 
> 设计的时候参考 [CleanArchitecture](https://github.com/jasontaylordev/CleanArchitecture)，某个 Command 或 Query 的 DTO 都跟随对应的 Command 或 Query，而不是拆开来，比如 [这个](https://github.com/jasontaylordev/CleanArchitecture/tree/main/src/Application/TodoLists/Queries/GetTodos)
> 
> PS：在 MaaDS 那里是拆开的，导致 MaaDS 现在乱的一批

那不改了。

> > 将全局配置统一到一个类中。使用全局的辅助类属性来统一获取各种配置，如环境变量、appsettings.json 中的配置等。
> 
> [ConfigurationHelper.cs](https://github.com/MaaAssistantArknights/MaaCopilotServer/blob/main/src/MaaCopilotServer.Api/Helper/ConfigurationHelper.cs)
> 
> ?

“将全局配置统一到**一个**类中。”

看这：[GlobalSettingsHelper.cs](https://github.com/MaaAssistantArknights/MaaCopilotServer/blob/dev/src/MaaCopilotServer.Api/Helper/GlobalSettingsHelper.cs)

----

既然这样那就先做“消除 implicit operator 运算符重载”这一项。

**Comment by LiamSho** [comment]
> 看这：[GlobalSettingsHelper.cs](https://github.com/MaaAssistantArknights/MaaCopilotServer/blob/dev/src/MaaCopilotServer.Api/Helper/GlobalSettingsHelper.cs)

我超

**Comment by LiamSho** [comment]
- [ ] 尝试不再使用 [PipelineException](https://github.com/MaaAssistantArknights/MaaCopilotServer/blob/dev/src/MaaCopilotServer.Application/Common/Exceptions/PipelineException.cs) 和 [MaaApiResponseHelper](https://github.com/MaaAssistantArknights/MaaCopilotServer/blob/dev/src/MaaCopilotServer.Application/Common/Helpers/MaaApiResponseHelper.cs)，使用 [custom-formatters](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-6.0) 进行返回值格式统一
