### ISSUE TITLE
OrderBy ID desc 在prod 没用

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaCopilotServer#46]
RT。 

![image](https://user-images.githubusercontent.com/33809511/176611831-8c43f7f4-6998-46d7-a300-aae20f4e3a8c.png)

**Comment by LiamSho** [comment]
你 URL 是啥倒是发一下啊（

PS：好像 Swagger 文档里面的描述有错误（~~GitHub Copilot 你坏事做尽~~）

https://api.prts.plus/copilot/query?desc=true

<img width="704" alt="image" src="https://user-images.githubusercontent.com/28832398/176733231-4ca04043-f6a8-4769-aa59-10b9311965b7.png">

https://api.prts.plus/copilot/query

<img width="704" alt="image" src="https://user-images.githubusercontent.com/28832398/176733329-07494197-279e-4f62-a96d-d531011860eb.png">

**Comment by Shawnsdaddy** [comment]
> 你 URL 是啥倒是发一下啊（
> 
> PS：好像 Swagger 文档里面的描述有错误（~GitHub Copilot 你坏事做尽~）
> 
> https://api.prts.plus/copilot/query?desc=true
> 
> <img alt="image" width="704" src="https://user-images.githubusercontent.com/28832398/176733231-4ca04043-f6a8-4769-aa59-10b9311965b7.png">
> 
> https://api.prts.plus/copilot/query
> 
> <img alt="image" width="704" src="https://user-images.githubusercontent.com/28832398/176733329-07494197-279e-4f62-a96d-d531011860eb.png">

我以为 desc 是 by default

**Comment by Shawnsdaddy** [comment]
BTW 得想个法子比如说优先排序当前活动的作业

**Comment by LiamSho** [comment]
#45
