### ISSUE TITLE
上传失败。。

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaCopilotServer#6]
Content: "{\"actions\":[{\"type\":\"部署\",\"name\":\"山\",\"location\":[9,3],\"direction\":\"下\"},{\"type\":\"部署\",\"name\":\"棘刺\",\"location\":[1,3],\"direction\":\"右\"},{\"type\":\"部署\",\"name\":\"桃金娘\",\"location\":[5,4],\"direction\":\"下\"},{\"type\":\"部署\",\"name\":\"流明\",\"location\":[3,5],\"direction\":\"上\"},{\"type\":\"部署\",\"name\":\"假日威龙陈\",\"location\":[7,3],\"direction\":\"右\"},{\"type\":\"部署\",\"name\":\"白面鸮\",\"location\":[6,4],\"direction\":\"右\"},{\"type\":\"部署\",\"name\":\"塞雷娅\",\"location\":[9,4],\"direction\":\"下\"},{\"type\":\"技能\",\"name\":\"假日威龙陈\",\"kills\":10,\"location\":[null,null]},{\"type\":\"技能\",\"kills\":31,\"name\":\"假日威龙陈\",\"location\":[null,null]},{\"type\":\"技能\",\"name\":\"白面鸮\",\"location\":[null,null]}],\"stage_name\":\"命运\",\"doc\":{\"details\":\"作者：YueShen\"},\"opers\":[{\"name\":\"山\",\"skill\":2,\"skill_usage\":2},{\"name\":\"棘刺\",\"skill\":3,\"skill_usage\":1},{\"name\":\"白面鸮\",\"skill\":2},{\"name\":\"流明\",\"skill\":3,\"skill_usage\":2},{\"name\":\"假日威龙陈\",\"skill\":3},{\"name\":\"桃金娘\",\"skill\":1,\"skill_usage\":1},{\"name\":\"塞雷娅\",\"skill\":1}]}"

说JSON 不合法

**Comment by Shawnsdaddy** [comment]
{"Content":"{\"actions\":[{\"type\":\"二倍速\"},{\"type\":\"部署\",\"name\":\"推进之王\",\"location\":[6,5],\"direction\":\"右\"},{\"type\":\"部署\",\"name\":\"煌\",\"location\":[7,5],\"direction\":\"右\"},{\"type\":\"部署\",\"name\":\"塞雷娅\",\"location\":[8,5],\"direction\":\"右\"}],\"stage_name\":\"LE-4\",\"doc\":{\"details\":\"BV1Ag41197\",\"title\":\"LE-4\"},\"opers\":[{\"name\":\"煌\",\"skill\":2,\"skill_usage\":0},{\"name\":\"推进之王\",\"skill\":2,\"skill_usage\":0},{\"name\":\"塞雷娅\",\"skill\":1,\"skill_usage\":0}]}"}

**Comment by LiamSho** [comment]
你minimum_required字段捏？

**Comment by Shawnsdaddy** [comment]
@LiamSho 问写json的那个哈哈
