### ISSUE TITLE
代码解耦合

### ISSUE THREAD

**Issue by LYZhelloworld** [MaaAssistantArknights/MaaCopilotServer#67]
希望以下地方可以替换成依赖注入：

## `MaaCopilotServer.Api.Jobs.ArknightsDataUpdate`
- `RunJob`：`new MaaCopilotDbContext(_dbOptions)` 替换为注入 `IMaaCopilotDbContext`
- `GetParsedData`、`GetDataVersion`：`HttpClientHandler` 想办法替换成依赖注入

## `MaaCopilotServer.Api.Jobs.TokenValidationCheck`
- 同上，`MaaCopilotDbContext`

## `MaaCopilotServer.Api.Middleware.ApmTransactionMiddleware`
- `Elastic.Apm.Agent.Tracer` 创建包装类 (wrapper class)

## `MaaCopilotServer.Application.Common.Extensions.DirectoryInfoExtension`
- 看一下这个：https://www.nuget.org/packages/System.IO.Abstractions

## `MaaCopilotServer.Application.Common.Extensions.FileInfoExtension`
- 同上

## `MaaCopilotServer.Infrastructure.Services.CopilotOperationService`
- `EncodeId`：这么简单的逻辑为什么不写成静态类？已经帮你提出来了，建议替换掉。
- `DecodeId`：同上

**Comment by LiamSho** [comment]
> MaaCopilotServer.Api.Jobs.ArknightsDataUpdate
> MaaCopilotServer.Api.Jobs.TokenValidationCheck

这个不好搞，Job 是 Singleton，而 DB 是 Scoped（

> MaaCopilotServer.Api.Middleware.ApmTransactionMiddleware

咋搞？。。。

> MaaCopilotServer.Application.Common.Extensions.DirectoryInfoExtension

简单的逻辑我有必要再引用一个库吗（

**Comment by LYZhelloworld** [comment]
> > MaaCopilotServer.Api.Jobs.ArknightsDataUpdate
> > MaaCopilotServer.Api.Jobs.TokenValidationCheck
>
> 这个不好搞，Job 是 Singleton，而 DB 是 Scoped（

啊，可是我这部分写完了啊。
