### ISSUE TITLE
作业分享站是不是出了什么问题

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaCopilotServer#69]
![image](https://user-images.githubusercontent.com/72590023/181127282-ff1e2831-618f-4f23-94a5-ba2b4b9222c6.png)
怎么显示不出作业了

**Comment by LiamSho** [comment]
因为就是没有（

**Comment by one-pyy** [comment]
(啊这, 我记得以前进去是有的啊233)

**Comment by LiamSho** [comment]
那你该去更新一下自己的信息了

这种问题应该去群里问而不是在gh
