### ISSUE TITLE
增加字段以区分 `普通`，`突袭`，`突袭且兼容普通` 难度

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaCopilotServer#73]
因为普通和突袭 `levelid` 是一样的。。

core 这边用不上这个字段，怎么方便怎么来，加作业 json 里也行，单独一个字段也行

**Comment by MistEO** [comment]
Alisa 说找你（

**Comment by LYZhelloworld** [comment]
# 为战斗流程 JSON 增加关卡难度字段

## 问题描述
目前战斗流程 JSON 文件中只有 `stage_name` 字段用于区分关卡，但无法区分关卡难度。

## 解决办法
添加新字段，用于存储难度信息。

一份作业可能有以下几种情况：
- 仅支持普通难度
- 仅支持突袭难度
- 二者皆可

建议做成按位枚举以便将来扩展。

**Comment by LYZhelloworld** [comment]
## 技术实现
### 战斗流程 JSON 改动
在战斗流程 JSON 中添加 `difficulty` 字段，取值如下：
- `0 (0b00)`：默认值，难度信息未知（用于兼容以前的版本）
- `1 (0b01)`：支持普通难度。
- `2 (0b10)`：支持突袭难度。
- `3 (0b11)`：支持普通和突袭难度。

其中 `3` 为 `1` 和 `2` 按位或得来。

### 数据库改动
（@LiamSho 需要你的帮助。）

在 `CopilotOperations` 表添加新列 `Difficulty`。如果数据库实体能用枚举最好，不能的话用 `int` 也可。

### 业务逻辑改动
`CreateCopilotOperation`、`UpdateCopilotOperation`、`GetCopilotOperation`、`QueryCopilotOperations` 相关部分加入新字段。

**Comment by LYZhelloworld** [comment]
已完成。 @MistEO 
- c0ee53b8de8592a52bfb80e9b76fd14ff2ad2f08
- 5bdfae99a488f3f35ed5c56b2ca66627592392df

**Comment by MistEO** [comment]
cc @martinwang2022 @GalvinGao

**Comment by MistEO** [comment]
cc @martinwang2002 @GalvinGao
