### ISSUE TITLE
我们不要用 `dev` 分支了吧

### ISSUE THREAD

**Issue by LYZhelloworld** [MaaAssistantArknights/MaaCopilotServer#74]
感觉没用。把 `main` 锁上，需要加新功能的时候直接创建自己的分支，拉取请求合并到 `main`。至于 `main` 什么时候发版那可以稍后决定。`dev` 的话攒了一大堆东西最后即使审查也看不懂了。

----

根据以下规则开发：

1. `main` 分支全程上锁。
2. 新功能创建自己的功能分支。
3. 新功能开发及测试完毕后创建到 `main` 的拉取请求，并在拉取请求中详细描述该功能的作用。
4. 合并至 `main` 后删除功能分支。合并方式待定，merge、squach、rebase 皆可。
5. 如果发现 `main` 分支上测试不正常，回退该拉取请求。
6. 如果测试正常则发布新版本。

**Comment by MistEO** [comment]
附议。

放 dev 上也没人帮我们测试，而且后端更新是无感知的，没有用户成本。写完了没啥问题直接进呗，我感觉没要必要搞一个版本一个版本的。
