### ISSUE TITLE
新增支持 `cooling` 字段

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaCopilotServer#97]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/69b2996d09765a9cb2fdded5b0c03b769f6f2334

[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md)

**Comment by martinwang2002** [comment]
link updates:
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.3-%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md
